name: Post Prevision New Account Custom Steps
description: "This is a stub example of how to add custom logic to run after account provisioning"
inputs:
  PIPELINES_GRUNTWORK_READ_TOKEN:
    description: "The GitHub token to use for checking out code from Gruntwork repo"
    required: true
  PIPELINES_CUSTOMER_ORG_READ_TOKEN:
    description: "The GitHub token to use for checking out code from the customer repo"
    required: true
  INFRA_ROOT_WRITE_TOKEN:
    description: "The INFRA_ROOT_WRITE_TOKEN secret"
    required: true
  gruntwork_context:
    description: "Gruntwork Context From the Gruntwork Bootstrap step"
    required: true
  baseline_path:
    description: "The path to the baseline files"
    required: true
runs:
  using: composite
  steps:
    - name: Custom Logic Goes Here
      shell: bash
      run: |
        exit 0